<?php

/*
|--------------------------------------------------------------------------
| Experience catalogue (seed data)
|--------------------------------------------------------------------------
| Prices are "from" prices in TTD taken from the client's previous site listing
| (search snapshot, 2026). CONFIRM every price and inclusion with the client.
| price_type: person (per guest), group (flat price for the group), hour (per hour).
| scene: which illustrated scene the card uses (reef, sunset, forest, night, island, spa, fishing, speed).
*/

return [
    'categories' => [
        'island-tours' => ['name' => 'Island tours', 'blurb' => 'See the whole of Tobago by road with a guide who grew up here.', 'icon' => 'compass'],
        'boat-tours' => ['name' => 'Boat tours', 'blurb' => 'Glass-bottom boats, reef snorkelling and the famous Nylon Pool.', 'icon' => 'ship'],
        'water-sports' => ['name' => 'Water sports', 'blurb' => 'Jet skis, clear kayaks, tow rides and rafting on calm Caribbean water.', 'icon' => 'waves'],
        'wellness' => ['name' => 'Wellness', 'blurb' => 'Massages on the sand and slow afternoons.', 'icon' => 'leaf'],
        'packages' => ['name' => 'Full-day packages', 'blurb' => 'Two or three experiences stitched into one easy day with lunch.', 'icon' => 'sparkles'],
    ],

    'items' => [
        [
            'slug' => '360-island-tour',
            'name' => '360 Island Tour',
            'category' => 'island-tours',
            'scene' => 'island',
            'image_path' => 'images/experiences/360-island-tour.webp',
            'tagline' => 'The whole island in one unforgettable day.',
            'description' => 'Leave Crown Point after breakfast and circle Tobago along both coasts: the Atlantic side through Roxborough and Speyside, then back down the Caribbean side through Castara and Plymouth. Your guide stops wherever the view, the story or the food is worth it.',
            'highlights' => ['Argyle Waterfall, the tallest on the island', 'Lookout over Little Tobago and Goat Island at Speyside', 'The Mystery Tombstone in Plymouth', 'Fort King George and the Scarborough skyline', 'Local lunch stop at Castara or Parlatuvier'],
            'includes' => ['Private air-conditioned vehicle', 'Driver-guide', 'Hotel pickup and drop-off', 'Bottled water'],
            'excludes' => ['Lunch', 'Waterfall entry fee'],
            'duration' => '7 to 8 hours',
            'duration_hours' => 8,
            'price' => 1910,
            'price_type' => 'group',
            'min_guests' => 1,
            'max_guests' => 6,
            'child_policy' => 'Children of all ages welcome.',
            'featured' => true,
            'sort' => 1,
        ],
        [
            'slug' => 'buccoo-reef-nylon-pool-no-mans-land',
            'name' => 'Buccoo Reef, Nylon Pool & No Man\'s Land',
            'category' => 'boat-tours',
            'scene' => 'reef',
            'image_path' => 'images/experiences/buccoo-reef-nylon-pool-no-mans-land.webp',
            'tagline' => 'The classic Tobago boat trip, done properly.',
            'description' => 'Glass-bottom boat across Buccoo Reef with time to snorkel the coral gardens, a swim in the waist-deep Nylon Pool in the middle of the sea, then a beach stop at No Man\'s Land with a cooler on the sand.',
            'highlights' => ['Snorkel Buccoo Reef marine park', 'Float in the Nylon Pool', 'Beach time at No Man\'s Land', 'Rum punch on the way back'],
            'includes' => ['Glass-bottom boat', 'Snorkel gear and life jackets', 'Reef guide', 'Rum punch and soft drinks'],
            'excludes' => ['Lunch', 'Hotel pickup (available on request)'],
            'duration' => '2.5 to 3 hours',
            'duration_hours' => 3,
            'price' => 245,
            'price_type' => 'person',
            'min_guests' => 1,
            'max_guests' => 30,
            'child_policy' => 'Children 4 and over. Under 12 pay half.',
            'featured' => true,
            'sort' => 2,
        ],
        [
            'slug' => 'countryside-tour',
            'name' => 'Countryside Tour: Little Tobago, Lovers Bay & Waterfall',
            'category' => 'packages',
            'scene' => 'forest',
            'image_path' => 'images/experiences/countryside-tour.webp',
            'tagline' => 'Rainforest, seabirds and a bay you can only reach by boat.',
            'description' => 'Drive the Windward coast to Speyside, cross by boat to Little Tobago for the bird sanctuary trail, snorkel over Angel Reef, then land at Lovers Bay, a pink-sand cove with no road in. A rainforest waterfall stop finishes the day.',
            'highlights' => ['Boat to Little Tobago bird sanctuary', 'Snorkel Angel Reef', 'Lovers Bay pink-sand beach', 'Waterfall swim'],
            'includes' => ['Transport from Crown Point', 'Boat crossing', 'Snorkel gear', 'Guide'],
            'excludes' => ['Lunch', 'Sanctuary and waterfall fees'],
            'duration' => 'Full day, about 9 hours',
            'duration_hours' => 9,
            'price' => 2000,
            'price_type' => 'group',
            'min_guests' => 2,
            'max_guests' => 6,
            'child_policy' => 'Children 6 and over.',
            'featured' => true,
            'sort' => 3,
        ],
        [
            'slug' => 'cotton-bay-coastal-tour-snorkeling',
            'name' => 'Cotton Bay, Coastal Tour & Snorkelling',
            'category' => 'island-tours',
            'scene' => 'sunset',
            'image_path' => 'images/experiences/cotton-bay-coastal-tour-snorkeling.webp',
            'tagline' => 'Caribbean-coast villages, hidden bays and the clearest water.',
            'description' => 'A slow drive up the leeward coast through Castara, Englishman\'s Bay and Parlatuvier, with a snorkel stop and a quiet afternoon at Cotton Bay, one of the least-visited beaches on the island.',
            'highlights' => ['Englishman\'s Bay', 'Parlatuvier lookout', 'Snorkel stop', 'Cotton Bay beach'],
            'includes' => ['Private vehicle', 'Guide', 'Snorkel gear', 'Hotel pickup'],
            'excludes' => ['Lunch'],
            'duration' => '6 to 7 hours',
            'duration_hours' => 7,
            'price' => 2040,
            'price_type' => 'group',
            'min_guests' => 2,
            'max_guests' => 6,
            'child_policy' => 'Children of all ages welcome.',
            'featured' => false,
            'sort' => 4,
        ],
        [
            'slug' => 'pirates-bay-lovers-bay',
            'name' => 'Pirates Bay & Lovers Bay by Boat',
            'category' => 'boat-tours',
            'scene' => 'sunset',
            'image_path' => 'images/experiences/pirates-bay-lovers-bay.webp',
            'tagline' => 'Two of the prettiest bays in the Caribbean, from the water.',
            'description' => 'From Charlotteville, a boat run to Pirates Bay and on to Lovers Bay with snorkelling and swimming at both. Combine with the drive up the coast for a full day.',
            'highlights' => ['Pirates Bay', 'Lovers Bay', 'Snorkelling at both bays'],
            'includes' => ['Boat', 'Snorkel gear', 'Life jackets', 'Captain'],
            'excludes' => ['Transport to Charlotteville (add on request)'],
            'duration' => '2 to 3 hours on the water',
            'duration_hours' => 3,
            'price' => 400,
            'price_type' => 'person',
            'min_guests' => 2,
            'max_guests' => 10,
            'child_policy' => 'Children 4 and over.',
            'featured' => false,
            'sort' => 5,
        ],
        [
            'slug' => 'bamboo-rafting-no-mans-land',
            'name' => 'Bamboo Rafting & No Man\'s Land',
            'category' => 'water-sports',
            'scene' => 'reef',
            'image_path' => 'images/experiences/bamboo-rafting-no-mans-land.webp',
            'tagline' => 'Drift the lagoon on a bamboo raft, then beach it.',
            'description' => 'A gentle paddle on a hand-built bamboo raft through the Bon Accord lagoon mangroves, ending with time on the sand at No Man\'s Land.',
            'highlights' => ['Mangrove lagoon', 'Bamboo raft', 'No Man\'s Land beach'],
            'includes' => ['Raft and guide', 'Life jackets', 'Drinks'],
            'excludes' => ['Lunch'],
            'duration' => '2 hours',
            'duration_hours' => 2,
            'price' => 700,
            'price_type' => 'group',
            'min_guests' => 2,
            'max_guests' => 6,
            'child_policy' => 'Children of all ages with an adult.',
            'featured' => false,
            'sort' => 6,
        ],
        [
            'slug' => 'double-clear-kayaking',
            'name' => 'Double Clear Kayaking',
            'category' => 'water-sports',
            'scene' => 'reef',
            'image_path' => 'images/experiences/double-clear-kayaking.webp',
            'tagline' => 'See-through kayaks over the reef. Yes, the photos are real.',
            'description' => 'Two-seat transparent kayaks launched from the beach at Pigeon Point or Store Bay. Paddle over seagrass, coral and turtles with the water right under you. Our guide takes photos for you.',
            'highlights' => ['Fully transparent two-seat kayak', 'Turtle and starfish spotting', 'Photos included'],
            'includes' => ['Kayak for two', 'Life jackets', 'Guide', 'Photos'],
            'excludes' => [],
            'duration' => '1 hour',
            'duration_hours' => 1,
            'price' => 350,
            'price_type' => 'group',
            'min_guests' => 1,
            'max_guests' => 2,
            'child_policy' => 'Children 5 and over with an adult.',
            'featured' => true,
            'sort' => 7,
        ],
        [
            'slug' => 'night-clear-kayaking',
            'name' => 'Night Clear Kayaking',
            'category' => 'water-sports',
            'scene' => 'night',
            'image_path' => 'images/experiences/night-clear-kayaking.webp',
            'tagline' => 'LED-lit kayaks under the stars.',
            'description' => 'The clear kayaks fitted with LED lights, paddled after dark on calm water. The light pulls in fish and the sky does the rest.',
            'highlights' => ['LED-lit transparent kayak', 'Calm night water', 'Stars and bioluminescence on the right nights'],
            'includes' => ['Lit kayak for two', 'Life jackets', 'Guide'],
            'excludes' => [],
            'duration' => '1 hour',
            'duration_hours' => 1,
            'price' => 455,
            'price_type' => 'group',
            'min_guests' => 1,
            'max_guests' => 2,
            'child_policy' => 'Children 8 and over with an adult.',
            'featured' => false,
            'sort' => 8,
        ],
        [
            'slug' => 'clear-kayak-floral-shoot',
            'name' => 'Clear Kayak Floral Photoshoot',
            'category' => 'water-sports',
            'scene' => 'reef',
            'image_path' => 'images/experiences/clear-kayak-floral-shoot.webp',
            'tagline' => 'A flower-filled clear kayak and a photographer. Proposals welcome.',
            'description' => 'The clear kayak dressed in fresh flowers, a professional photographer on the beach and in the water, and an hour of golden light. Built for proposals, anniversaries and birthdays.',
            'highlights' => ['Flower-dressed kayak', 'Professional photographer', 'Edited photos within 48 hours'],
            'includes' => ['Kayak styling', 'Photographer (1 hour)', '30 edited photos'],
            'excludes' => [],
            'duration' => '1.5 hours',
            'duration_hours' => 2,
            'price' => 1995,
            'price_type' => 'group',
            'min_guests' => 1,
            'max_guests' => 2,
            'child_policy' => 'Any age.',
            'featured' => false,
            'sort' => 9,
        ],
        [
            'slug' => 'jet-skiing',
            'name' => 'Jet Skiing',
            'category' => 'water-sports',
            'scene' => 'speed',
            'image_path' => 'images/experiences/jet-skiing.webp',
            'tagline' => 'Thirty minutes of throttle off Pigeon Point.',
            'description' => 'Modern jet skis with a safety briefing and a marked course off the beach. Ride solo or two-up.',
            'highlights' => ['30-minute ride', 'Two-up allowed', 'Safety briefing included'],
            'includes' => ['Jet ski', 'Life jackets', 'Briefing'],
            'excludes' => [],
            'duration' => '30 minutes',
            'duration_hours' => 1,
            'price' => 350,
            'price_type' => 'group',
            'min_guests' => 1,
            'max_guests' => 2,
            'child_policy' => 'Riders 16 and over. Passengers 8 and over.',
            'featured' => false,
            'sort' => 10,
        ],
        [
            'slug' => 'super-mable-tow-ride',
            'name' => 'Super Mable Tow Ride',
            'category' => 'water-sports',
            'scene' => 'speed',
            'image_path' => 'images/experiences/super-mable-tow-ride.webp',
            'tagline' => 'Three seats, one boat, a lot of screaming.',
            'description' => 'The inflatable Super Mable towed behind a speedboat off Store Bay. Up to three riders at once.',
            'highlights' => ['Up to 3 riders', '15-minute ride', 'Boat captain controls the speed'],
            'includes' => ['Tow ride', 'Life jackets'],
            'excludes' => [],
            'duration' => '15 minutes',
            'duration_hours' => 1,
            'price' => 300,
            'price_type' => 'person',
            'min_guests' => 1,
            'max_guests' => 3,
            'child_policy' => 'Riders 10 and over.',
            'featured' => false,
            'sort' => 11,
        ],
        [
            'slug' => 'beach-massages',
            'name' => 'Beach Massage',
            'category' => 'wellness',
            'scene' => 'spa',
            'image_path' => 'images/experiences/beach-massages.webp',
            'tagline' => 'A massage table on the sand, the sea as the soundtrack.',
            'description' => 'A certified therapist sets up on the beach at your resort or at Pigeon Point. Swedish or deep tissue, 60 or 90 minutes.',
            'highlights' => ['Certified therapist', 'Beachfront or at your villa', 'Couples option'],
            'includes' => ['Table, oils and linens', 'Therapist travel within Crown Point'],
            'excludes' => [],
            'duration' => '60 or 90 minutes',
            'duration_hours' => 1,
            'price' => 700,
            'price_type' => 'person',
            'min_guests' => 1,
            'max_guests' => 4,
            'child_policy' => 'Adults only.',
            'featured' => false,
            'sort' => 12,
        ],
        [
            'slug' => 'private-fishing-charter',
            'name' => 'Private Fishing Charter',
            'category' => 'boat-tours',
            'scene' => 'fishing',
            'image_path' => 'images/experiences/private-fishing-charter.webp',
            'tagline' => 'Half a day trolling for wahoo, mahi and tuna.',
            'description' => 'A private boat with captain and tackle out of Buccoo or Charlotteville. Keep what you catch and we can have a restaurant cook it the same night.',
            'highlights' => ['Private boat and captain', 'All tackle and bait', 'Keep your catch'],
            'includes' => ['Boat (4 hours)', 'Captain and mate', 'Tackle, bait, ice', 'Drinks'],
            'excludes' => ['Lunch'],
            'duration' => '4 hours',
            'duration_hours' => 4,
            'price' => 3500,
            'price_type' => 'group',
            'min_guests' => 1,
            'max_guests' => 4,
            'child_policy' => 'Children 8 and over.',
            'featured' => false,
            'sort' => 13,
        ],
    ],

    /*
    | Stock photos bundled in public/images/experiences. Most are Creative Commons and require
    | attribution, which the /photo-credits page provides. Replace with the client's own photos
    | via Admin > Experiences whenever possible.
    */
    'photo_credits' => [
        '360-island-tour' => ['title' => 'Parlatuvier Bay view (2009a)', 'author' => 'cheesy42', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Parlatuvier_Bay_view_(2009a).jpg'],
        'buccoo-reef-nylon-pool-no-mans-land' => ['title' => 'Tobago nylon pool', 'author' => 'Darkonc', 'license' => 'CC BY-SA 3.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/3.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Tobago_nylon_pool.jpg'],
        'countryside-tour' => ['title' => 'Toraille Waterfall', 'author' => 'Aneil Lutchman', 'license' => 'CC BY-SA 2.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/2.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Toraille_Waterfall.JPG'],
        'cotton-bay-coastal-tour-snorkeling' => ['title' => 'Castara Bay (Tobago 2009)', 'author' => 'cheesy42', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Castara_Bay_(Tobago_2009).jpg'],
        'pirates-bay-lovers-bay' => ['title' => 'Sunset at Pigeon Point, Tobago', 'author' => 'sarah moolchan', 'license' => 'CC BY-SA 3.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/3.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Sunset_at_Pigeon_Point_,_Tobago_-_panoramio.jpg'],
        'bamboo-rafting-no-mans-land' => ['title' => 'Shallow waters (Buccoo Reef)', 'author' => 'WhatsupDarren', 'license' => 'CC BY-SA 4.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/4.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Shallow_waters.jpg'],
        'double-clear-kayaking' => ['title' => 'Clear kayaks - crystal kayaks - Anse Source d\'Argent - La Digue - Seychelles - 1', 'author' => 'NorbertNagel', 'license' => 'CC BY-SA 4.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/4.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Clear_kayaks_-_crystal_kayaks_-_Anse_Source_d%27Argent_-_La_Digue_-_Seychelles_-_1.jpg'],
        'night-clear-kayaking' => ['title' => 'Kayaking in Florida at sunset', 'author' => 'U.S. Fish and Wildlife Service Southeast Region', 'license' => 'Public domain', 'license_url' => '', 'source' => 'https://commons.wikimedia.org/wiki/File:Kayaking_in_Florida_at_sunset.jpg'],
        'clear-kayak-floral-shoot' => ['title' => 'Clear kayaks - crystal kayaks - Anse Source d\'Argent - La Digue - Seychelles - 2', 'author' => 'NorbertNagel', 'license' => 'CC BY-SA 4.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/4.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Clear_kayaks_-_crystal_kayaks_-_Anse_Source_d%27Argent_-_La_Digue_-_Seychelles_-_2.jpg'],
        'jet-skiing' => ['title' => 'Jet Skiing - Mahe - Seychelles - 2025', 'author' => 'NorbertNagel', 'license' => 'CC BY-SA 4.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/4.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Jet_Skiing_-_Mahe_-_Seychelles_-_2025.jpg'],
        'super-mable-tow-ride' => ['title' => 'The thrill seekers', 'author' => 'Bernard Spragg', 'license' => 'Public domain', 'license_url' => '', 'source' => 'https://commons.wikimedia.org/wiki/File:%22The_thrill_seekers%22_(52764889291).jpg'],
        'beach-massages' => ['title' => 'Pigeon Point beach', 'author' => 'Kp93', 'license' => 'CC BY-SA 3.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/3.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Pigeon_Point_beach.jpg'],
        'private-fishing-charter' => ['title' => 'Charter fishing boat in Hawaii', 'author' => 'Adam', 'license' => 'CC BY-SA 2.0', 'license_url' => 'https://creativecommons.org/licenses/by-sa/2.0/', 'source' => 'https://commons.wikimedia.org/wiki/File:Charter_fishing_boat_in_Hawaii.jpg'],
    ],
];
